name: pym3t

channels:
  - conda-forge
  - pytorch
  - defaults

dependencies:
  - nvidia::cuda-toolkit=11.8.0
  - python=3.10
  - pytorch::pytorch=2.1.0
  - torchvision=0.16.0
  - compilers=1.7.0
  - cmake=3.29.6
  - scikit-build=0.17.6
  - pyyaml=6.0.1
  - opencv=4.10.0
  - mesa-libgl-devel-cos7-x86_64=18.3.4
  - mesa-dri-drivers-cos7-x86_64=18.3.4
  - libxcb=1.15
  - glew=2.1.0
  - glfw=3.4
  - librealsense=2.54.2
  - quaternion=2023.0.3
  - eigen=3.4.0
  - pip=24.0
  - pip:
    - nanobind==2.0.0
    - tabulate==0.9.0
    - matplotlib==3.8.4
    - timm==0.9.10
    - torchinfo==1.8.0
    - omegaconf==2.3.0
    - git+https://github.com/ChaoningZhang/MobileSAM.git