dataset_name: rbot
dataset_dir: data/RBOT

model: ape
scene: a_regular

image_size:
  height: 512
  width: 640

geometry_unit_in_meter: 0.001

# Modality to use for tracking
# (region_modality or deep_region_modality)
modality: region_modality

# Metrics to evaluate
metrics:
  - cm_degree_score:
      threshold_trans: 5
      threshold_rot: 5

# Whether to reset the pose of the object if the tracking is lost regarding
# the given criterion
reset_pose:
  do_reset: true
  criterion:
    cm_degree_score:
      threshold_trans: 5
      threshold_rot: 5

# Number of images (the first image of the sequence is not counted)
nb_images: 1000

display_images: false

log_dir: logs
