dataset_name: rbot
dataset_dir: data/RBOT_dataset_raw

image_size:
  height: 512
  width: 640

geometry_unit_in_meter: 0.001

# Modality to use for tracking
# (region_modality or deep_region_modality or deep_clines_region_modality)
modality: deep_clines_region_modality

# Whether to reset the pose of the object if the tracking is lost regarding
# the given criterion
reset_pose:
  do_reset: true
  criterion:
    CmDegreeScore:
      threshold_trans: 5
      threshold_rot: 5

# Choose the scenes and models to evaluate
# scenes_models_dict:
#   a_regular:
#     - ape
#     - cat
#   b_dynamiclight:
#     - ape
#     - phone

# To evaluate all scenes and models, use the following
scenes_models_dict: all

# Number of images (the first image of the sequence is not counted)
nb_images_per_sequence: 1000

log_dir: logs