dataset_name: bcot
dataset_dir: data/BCOT

model: Ape
scene: easy_static_handheld

image_size:
  height: 512
  width: 640

geometry_unit_in_meter: 0.001

# Modality to use for tracking
# (region_modality or deep_region_modality or deep_clines_region_modality)
modality: deep_clines_region_modality

# Whether to reset the pose of the object if the tracking is lost regarding
# the given criterion
reset_pose:
  do_reset: true
  criterion:
    CmDegreeScore:
      threshold_trans: 5
      threshold_rot: 5

# Number of images (the first image of the sequence is not counted)
nb_images: null  # null means all images

display_images: true

log_dir: logs
